### ISSUE TITLE
potential_B ignored?

### ISSUE THREAD

**Issue by pietromassignan** [trotter-suzuki-mpi/trotter-suzuki-mpi#109]
I seem to find that, if two potentials are given, only pot_A is used, for both components, and pot_B is ignored

**Comment by Lucacalderaro** [comment]
Commit d5ab2952b8a017899091793a60a23944fdb3913c fixes the issue.

**Comment by peterwittek** [comment]
Commit 386bacfcb9dd0cf74ccdfcaf326ab3825aec1be1 also fixes it. We can double-close this.
