### ISSUE TITLE
Norm not conserved during imagTime evolution

### ISSUE THREAD

**Issue by pietromassignan** [trotter-suzuki-mpi/trotter-suzuki-mpi#116]
Under some conditions, the solver for the two-component gas doesn't conserve the norms of the two wavefunctions during imaginary time evolution

e.g., a run with Omega_Rabi=0, and g_a different from g_b, yields

('Squared norm of states a and b before imaginary evolution: ', 1.000000000000021, 1.000000000000021)
...
('Squared norm of states a and b after imaginary evolution: ', 7.191011276021154e-103, 13173239.240033392)

**Comment by peterwittek** [comment]
Which kernel are you using?

**Comment by peterwittek** [comment]
I just noticed that the GPU kernel misses normalization entirely.

**Comment by peterwittek** [comment]
With commit d64a1400533d39bd28087d4fe37af17f9306281e, this is fixed.

@Lucacalderaro, the conditions for renormalization in imaginary time evolution are getting messy. It is now triggered when ``coupling_const[1] != 0 || coupling_const[3] != 0 || coupling_const[4] != 0``.  We can either remove the new condition ``coupling_const[1] != 0`` and renormalize the state at the end of imaginary time evolution in the Solver class, or we renormalize in each iteration irrespective of the coupling constants. What do you think?

**Comment by Lucacalderaro** [comment]
Commit 76357ab47faf634597fd18eda137805e7924ff76 should completely fix the issue.

In the case of 2GPE, two normalization are needed in each imaginary-time iteration. The evolution in the trotter-suzuki approximation can be divided into two steps: the first part of the evolution depends on H_1 and H_2, which are the Hamiltonians that act on the single wave functions (they do not depend on the Rabi coupling) and should change neither the norms of the single wave functions nor their sum; the second part depends on H_omega, which is the Hamiltonian controlling the Rabi coupling and it can change the norm of the single wave functions but not their sum. 
Then, we need to apply one single wave function normalization just after the H_1 and H_2 evolution and one normalization to the total wave function after the H_omega evolution. The latter is not necessary if omega=0.

@peterwittek please check whether this commit works with the GPU kernel.

**Comment by peterwittek** [comment]
Yes, it does. Thanks, it does simplify it a lot.
