### ISSUE TITLE
Density matrix sum

### ISSUE THREAD

**Issue by arlongx** [trotter-suzuki-mpi/trotter-suzuki-mpi#124]
The sum over all the matrix elements of state.get_particle_density() returns not 1, but some large number while state.get_squared_norm() returns 1. The sum also scales with the lattice size. 

An example code:

import numpy as np
from trottersuzuki import *

grid = Lattice(300, 20) 

potential = HarmonicPotential(grid, 1, 1)  
particle_mass = 1.
hamiltonian = Hamiltonian(grid, potential, particle_mass)   

frequency = 1
state = GaussianState(grid, frequency)  

time_of_single_iteration = 1.e-4
solver = Solver(grid, state, hamiltonian, time_of_single_iteration)  
print("Mod square: ",state.get_squared_norm())
print("Sum of density: ", np.sum(state.get_particle_density()))

number_of_iterations = 1000
solver.evolve(number_of_iterations)  # evolve the state of 1000 iterations

print("Mod square: ",state.get_squared_norm())
print("Sum of density: ", np.sum(state.get_particle_density()))

Output:
Mod square:  0.999999999999988
Sum of density:  225.0
Mod square:  1.0000000000007563
Sum of density:  225.0

**Comment by peterwittek** [comment]
I think a scaling factor went missing: the delta_x and delta_y were only factored in when calculating the norm. Please try commit c591fae19767ff578c6e0ff606fa6c29149ea36a.

**Comment by arlongx** [comment]
Thanks. I'm trying to get the commit using:
pip install git+https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi/commit/c591fae19767ff578c6e0ff606fa6c29149ea36a

But I get the error:

Command "git clone -q https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi/commit/c591fae19767ff578c6e0ff606fa6c29149ea36a /var/folders/67/7sfvxtm13ngck7n295mdck400000gp/T/pip-5eum5owz-build" failed with error code 128 in None

**Comment by peterwittek** [comment]
This will definitely not work because the repo is not pure Python. Please try running `python setup.py install --user`  after extracting [this file](https://github.com/trotter-suzuki-mpi/trotter-suzuki-mpi/files/295943/trottersuzuki-1.5.4.tar.gz)

**Comment by arlongx** [comment]
That works, now both add up to 1.

Mod square:  0.999999999999988
Sum of density:  1.0
Mod square:  1.0000000000007563
Sum of density:  1.0

Thanks Peter!

**Comment by peterwittek** [comment]
No worries. Just open an issue if you encounter any other problem.
