### ISSUE TITLE
angular velocity problem

### ISSUE THREAD

**Issue by antoniommateo** [trotter-suzuki-mpi/trotter-suzuki-mpi#129]
We are not able to introduce non-zero values of the angular velocity in the Hamiltonian. The system returns nan values for the energies.

**Comment by peterwittek** [comment]
Could you give a minimal working example to recreate the problem?

**Comment by peterwittek** [comment]
Did you also add the angular velocity to the lattice? The grid has to be aware of it because the halo is larger.

**Comment by antoniommateo** [comment]
No I did not. Let me check whether I can do it an comment on this. Thank
you.

**Comment by peterwittek** [comment]
Any news on this?

**Comment by antoniommateo** [comment]
Hi Peter, not yet (I was focusing on the instabilities), sure there is no
problem here. I was thinking of trying a toroidal trap with the obstacle
and then adding the omega, I think can be beautiful and so we can try the
moving reference frame we commented. I'll tell you.
Cheers,
Antonio

**Comment by peterwittek** [comment]
Commit e622c1376e5a334d07764375ab3f101ee7c43354 fixes this.
