### ISSUE TITLE
Error in example "Imaginary time evolution in a 1D lattice using radial coordinate"

### ISSUE THREAD

**Issue by BrunoNaylor** [trotter-suzuki-mpi/trotter-suzuki-mpi#162]
Hi,

We believe there is an error in "Imaginary time evolution in a 1D lattice using radial coordinate" for the theoretical ground state.

Replacing the following lines:
groundstate = ts.BesselState(grid, angular_momentum)
groundstate_psi = np.sqrt(groundstate.get_particle_density()[0])

with
 x0 = sp.jn_zeros(angular_momentum,1)
bess0 = sp.jv(angular_momentum,grid.get_x_axis()*x0/radius)
bess0 = bess0 / np.linalg.norm(bess0)

seems to resolve the problem.

best

**Comment by peterwittek** [comment]
@Lucacalderaro, do you have any insight on this?

**Comment by Lucacalderaro** [comment]
Hi,

thank you for reporting this issue. The function `get_particle_density` does not return a normalized function. To fix this we can add the line `groundstate_psi = groundstate_psi / np.linalg.norm(groundstate_psi)` (see the commit 27fa244dc25c72768e66b802e4d528d516f28e42); just to avoid importing scipy.

Cheers,
Luca
