### ISSUE TITLE
Different lattice resolution along x and y axes

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/trotter-suzuki-mpi#29]
Currently the physical distances between two neighbour points of the lattice along the x axis and the y axis must be equal. It would be good to have different distances.

**Comment by peterwittek** [comment]
The issue of 1D kernels (#83) is basically equivalent to setting dim_y=1. With pull request #127, the bugs around different spatial extensions probably went away, so we should consider adding the possibility of non-square grids and non-equivalent physical distances between grid points along x and y.

**Comment by peterwittek** [comment]
Commits 00d091058660ae0a6c8acd1eb36abc82b9ca4ebb and b9a832d75823e1f286f1e37468d1ec7d38fc95db solve this.
