### ISSUE TITLE
Fix example/Makefile.in to exclude cpublocksse when using Darwin

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/trotter-suzuki-mpi#36]

**Comment by peterwittek** [comment]
This is a deeper issue. The trouble is always with a few lines of special memory allocation in the SSE kernel. Many versions of GCC here, the problem is not restricted to Darwin and Windows. This problem is loosely related to #25: the SSE kernel is simply not well-maintained.

**Comment by peterwittek** [comment]
Actually, #24 is also related.

**Comment by peterwittek** [comment]
Commit 4fbaac18c2a9400d2825309e837ac66944d2f69a should fix this. SSE kernel support is now autodetected in the configure script and disables it globally if the support is not there.
