### ISSUE TITLE
The documentation needs to be updated

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/trotter-suzuki-mpi#43]

**Comment by Lucacalderaro** [comment]
The CPU kernel implements a solver for rotating systems. The documentation needs to be updated to account this new feature.

**Comment by peterwittek** [comment]
Please also make the respective new parameters optional.

**Comment by peterwittek** [comment]
1. The doxygen documentation is absent for the new class structure.
2. Perhaps the examples as files could be eliminated and added to the documentation.
3. A tutorial would be even better.
4. It would be good to have an automatic way to convert the doxygen documentation to docstrings, but it [might prove difficult](http://stackoverflow.com/questions/11435102/is-there-a-good-way-to-produce-documentation-for-swig-interfaces)

**Comment by peterwittek** [comment]
Commit 58815e29b8b7ff2ff618638d37407f3c6d682aa6 creates a decent structure for the doxygen documentation.
