### ISSUE TITLE
Integration of stamp and stamp_real into State class

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/trotter-suzuki-mpi#67]
Rename them to write_to_file.

We have the functions 'stamp' and 'stamp_real', which are well integrated with mpi. The former creates two files: one with the complex values of the state, and one with the real values of the state. The latter creates a single file with real values. I use the former to stamp the state and the latter to stamp density and phase matrices; see example 'harmonic_osc_real'.
It would be nice to integrate these functions with State class. For instance, we could add a parameter in get_phase and get_density, so that these can stamp the matrices they would return.

**Comment by peterwittek** [comment]
Please check if commit 1c0b1ae5e262a9c2a85e38787f4ac78859ca4e1f makes sense. If it does, we can close this.

**Comment by Lucacalderaro** [comment]
Yes thanks. There is still a bug, it is not writing any file.

Il giorno gio 7 gen 2016, 17:32 Peter Wittek <notifications@github.com> ha
scritto:

**Comment by peterwittek** [comment]
Thanks for fixing this. Then we can close it.
