### ISSUE TITLE
Unit tests are broken

### ISSUE THREAD

**Issue by peterwittek** [trotter-suzuki-mpi/trotter-suzuki-mpi#69]

**Comment by peterwittek** [comment]
The unit test now compiles, with commit 5726a0e5bd14df8657c76266f88ac4277dfd0b68. This is currently a not very elegant regression test. This should be modified as follows:

1. Calculations should finish after a few seconds.
2. The whole setting up the state, blah-blah, should be wrapped in a CppUnit test and compare against the correct values.
3. Apart from a single test of real time evolution with no external potential, we should have three more: imaginary time evolution with external potential, single-component BEC, two-component BEC.
4. Rinse and repeat for GPU kernel if available.

**Comment by Lucacalderaro** [comment]
Commit 8ff48e6e36f53a543cb4e3ca15de1817efc9154c adds a unit test for the cpu kernel. The tests are:

    1. free_particle_test: test the energy and norm conservation for a free particle, without any interaction.
    2. harmonic_oscillator_test: test the energy and norm conservation for a particle in a harmonic potential.
    3. imaginary_harmonic_oscillator_test: test norm conservation and whether the evolved state reach the ground state energy.
    4. intra_particle_interaction_test: test norm and energy conservation and whether the X^2 expected value is compatible with a gold standard value.
    5. imaginary_intra_particle_interaction_test: test norm conservation and whether the X^2 and energy expected values are compatible with gold standard values.
    6. mixed_BEC_test: test total norm and energy conservation and whether the norms of the single states exchange their values in half Rabi period.
    7. imaginary_mixed_BEC_test: test total norm conservation and whether the norms of the single states converge to half the value of total norm.

A unit test for GPU kernel may be compiled changing the string `#define KERNEL_TYPE "cpu"` in `cpukerneltest.cpp` or copying the cpu tests and adapting the KERNEL_TYPE string.

**Comment by peterwittek** [comment]
Thanks, this works great!

**Comment by peterwittek** [comment]
Please check if commit dc4d9a07d7390dba92b986bd0d570387904e3672 has the new default values correct. The lattice size was increased to accommodate the minimum lattice size of the hybrid kernel, and two baseline ``mean_XX`` were recalculated.

**Comment by peterwittek** [comment]
Note that the CPU kernel still chokes on this test:

    kerneltest.cpp:145:Assertion
    Test name: my_test<CpuKernelTest>::rotating_frame_of_reference_test
    assertion failed
    - Expression: std::abs(ini_tot_energy - tot_energy) < TOLERANCE*10.
