### ISSUE TITLE
State and potential definition in Python

### ISSUE THREAD

**Issue by peterwittek** [trotter-suzuki-mpi/trotter-suzuki-mpi#80]
Since [there is no simple mechanism](http://stackoverflow.com/questions/30437932/how-to-pass-python-function-as-an-argument-to-c-function-using-cython) to pass a Python function as an argument to a C++ function, the respective Python constructors should have a thin wrapper to take a Python function and generate a numpy array of appropriate dimensions, which then can be passed as a pointer to the C++ constructor.

There should be no other Python constructor but this. By doing so, we bypass the problems of padding the matrices that we struggled with earlier.

One problem to be solved: reading out the state. This returns the padded version, which might not be what the user expects.

**Comment by Lucacalderaro** [comment]
Commit 17878b573a2f8afe45a2e032c2b203cccb7a21b9 wraps all the classes and it adds a member in State and Potential to initialize the matrices with a python function.

**Comment by peterwittek** [comment]
This looks perfect.
