### ISSUE TITLE
1D kernels

### ISSUE THREAD

**Issue by peterwittek** [trotter-suzuki-mpi/trotter-suzuki-mpi#83]
This is a lot easier than issue #27. [GPELab](http://gpelab.math.cnrs.fr/) is also a relevant reference implementation here.

**Comment by peterwittek** [comment]
The 1D kernel works, more or less. From Python, this code shows a consistent norm:

```python
import trottersuzuki as ts
from numpy import sqrt

dim = 128
length = 20


def state_function(x):
    return sqrt(1/length)


def pot_function(x):
    return 0

grid = ts.Lattice1D(dim, length)
state = ts.State(grid)
state.init_state(state_function)
density = state.get_particle_density()
print(sum(density))
potential = ts.Potential(grid)
potential.init_potential(pot_function)
hamiltonian = ts.Hamiltonian(grid, potential)
time_of_single_iteration = 1.0e-3
solver = ts.Solver(grid, state, hamiltonian, time_of_single_iteration)
solver.evolve(100)
density = state.get_particle_density()
print(sum(density))
```
Some further testing is necessary before closing this. Also, it would be better to merge `cpublock.cpp` and `cpublock1d.cpp` in the same file, and then develop a 1D GPU kernel.

**Comment by dingliu0305** [comment]
I'm trying to create a 1D kernel test example based on the new code. But all state functions and potential functions are designed for 2D case. So, do we need to overload the constructors for 1D case ?

**Comment by peterwittek** [comment]
That is exactly what I did. The State and Potential classes are now aware of the underlying geometry, and the initializer functions were overloaded, as you can see in the example above. The idea was to avoid code duplication.

**Comment by peterwittek** [comment]
Commit c66aa1f217ca4375f2a33c6e0cb9cecf6e8fdb7d closes this.
