### ISSUE TITLE
MPI compilation fails on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by peterwittek** [trotter-suzuki-mpi/trotter-suzuki-mpi#88]
It is likely to affect users. The problem is probably with the MPI version. The error message is as follows:

    trotter-suzuki-mpi $ make
    make -C src all
    make[1]: Entering directory `/home/pwittek/trotter-suzuki-mpi/src'
    mpic++ -DHAVE_CONFIG_H -fPIC -fopenmp -Ofast -march=native -I/usr/lib/openmpi/include -iquote. -iquote.. -o common.o -c ./common.cpp
    ./common.cpp: In function ‘void stamp(Lattice*, State*, std::string)’:
    ./common.cpp:168:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
         MPI_File_open(grid->cartcomm, output_filename.str().c_str(),
                                                                   ^
    In file included from ./trottersuzuki.h:28:0,
                     from ./common.cpp:22:
    /usr/lib/openmpi/include/mpi.h:1146:20: error:   initializing argument 2 of ‘int MPI_File_open(MPI_Comm, char*, int, MPI_Info, ompi_file_t**)’ [-fpermissive]
     OMPI_DECLSPEC  int MPI_File_open(MPI_Comm comm, char *filename, int amode,
                        ^
    ./common.cpp:172:86: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
         MPI_File_set_view(file, 0,  MPI_CHAR, complex_localarray, "native", MPI_INFO_NULL);
                                                                                          ^
    ./common.cpp:200:63: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
         MPI_File_open(grid->cartcomm, output_filename.str().c_str(),
                                                                   ^
    In file included from ./trottersuzuki.h:28:0,
                     from ./common.cpp:22:
    /usr/lib/openmpi/include/mpi.h:1146:20: error:   initializing argument 2 of ‘int MPI_File_open(MPI_Comm, char*, int, MPI_Info, ompi_file_t**)’ [-fpermissive]
     OMPI_DECLSPEC  int MPI_File_open(MPI_Comm comm, char *filename, int amode,
                        ^
    ./common.cpp:204:78: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
         MPI_File_set_view(file, 0,  MPI_CHAR, localarray, "native", MPI_INFO_NULL);
                                                                                  ^
    ./common.cpp: In function ‘void stamp_matrix(Lattice*, double*, std::string)’:
    ./common.cpp:269:50: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
         MPI_File_open(grid->cartcomm, filename.c_str(),
                                                      ^
    In file included from ./trottersuzuki.h:28:0,
                     from ./common.cpp:22:
    /usr/lib/openmpi/include/mpi.h:1146:20: error:   initializing argument 2 of ‘int MPI_File_open(MPI_Comm, char*, int, MPI_Info, ompi_file_t**)’ [-fpermissive]
     OMPI_DECLSPEC  int MPI_File_open(MPI_Comm comm, char *filename, int amode,
                        ^
    ./common.cpp:273:78: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
         MPI_File_set_view(file, 0,  MPI_CHAR, localarray, "native", MPI_INFO_NULL);
                                                                                  ^
    make[1]: *** [common.o] Error 1
    make[1]: Leaving directory `/home/pwittek/trotter-suzuki-mpi/src'
    make: *** [all] Error 2

**Comment by Lucacalderaro** [comment]
Please check if commit 6086ecfadba712b9c1eb9a386429bc53ddd8eb4e fixes this issue.

**Comment by peterwittek** [comment]
That solves it. Thanks!
