### ISSUE TITLE
OpenMP #pragma commands in model.cpp and solver.cpp generate errors in python wrapper compilation

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/trotter-suzuki-mpi#89]

**Comment by Lucacalderaro** [comment]
I do not get why this occur, since the  #pragma command in cpublock does not create any problem.

**Comment by peterwittek** [comment]
Actually, the same problem arises when trying to compile the source without MPI. I think the source of the problem is that you try to reduce to array variables. You could try replacing sum_norm2[0] and sum_norm2[1] with two variables sum_norm2_0 and sum_norm2_1, and so on.

**Comment by Lucacalderaro** [comment]
I found out that the problem is that we are trying to implement the reduction for a complex type, which is currently not [supported](http://stackoverflow.com/questions/7163562/elegant-and-typical-workaround-for-openmp-reduction-on-complex-variable-in-c)

Then the solution would be to use two double types for each complex type and the two real() and imag() functions. Is it worth using so many variables for the reduction?

**Comment by peterwittek** [comment]
I think so. Especially if we want frequent samples of the expectation values.

**Comment by Lucacalderaro** [comment]
Commit fcc3ac073097b676a6d0386e8116f48daac79c8c fixes the compilation issue. The `calculate_expected_values` functions in `model.cpp` and `solver.cpp` give wrong values when using OpenMP.

**Comment by peterwittek** [comment]
There are race conditions due to shared variables. In `model.cpp`, they are now resolved with commit b1678a8ad7f6307cfca9dc14c6fb8440d134b5ea. Please do the same for `solver.cpp`.

**Comment by Lucacalderaro** [comment]
Thanks, commit 0b265d01172e7282d6eb712c876fdba93fd41642 fixes the issue.
