### ISSUE TITLE
Lattice halo independence

### ISSUE THREAD

**Issue by Lucacalderaro** [trotter-suzuki-mpi/trotter-suzuki-mpi#90]
Currently the halo's width of the lattice depends on the value of `omega`, which is the angular velocity of the frame of reference. This feature is a bit awkward, since it would make more sense if the angular velocity was uniquely a paramenter of the Hamiltonian. On the other hand, when the angular velocity is not zero, the halo needs to be at least 8 grid points, instead of the usual 4. Indeed, in this case the angular momentum operator is present in the Hamiltonian and its exponential acts on couples of the grid points, akin to the kinetic operator.

The question is: should we make the halo's width independent from the angular velocity, fixing it to 8? Of course this choice leads to a worse performance.

**Comment by peterwittek** [comment]
It is awkward for sure. Could you make a handful of benchmarks to see how much performance we would lose if we use a halo of 8 points? Especially in the MPI version that actually sends the halos around.

**Comment by Lucacalderaro** [comment]
The Lattice depends on halo width only when boundary conditions are closed and mpi_procs >1. Since Python and MATLAB wrappers works without MPI, these conditions are not met, for them the Lattice is independent from the halo width.

As regards the C++ implementation, commit 2561a900e92777052f58fe119d2aa942956b73c2 adds a test at the Hamiltonian constructor to check that the Lattice object was created correctly.
